# This file tells Google Cloud Build what to do on every push

steps:
# -----------------------------------------------------------------
# --- STEP 1: Build the Docker image explicitly ---
# We use 'docker build' and tell it *exactly* which file to use.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag'
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ghumakkad-repo/ghumakkad-backend:latest'
  - '--file'
  - 'Dockerfile'  # <-- We use the (now correctly named) Dockerfile
  - '.'

# --- STEP 2: Push the built image ---
# We now explicitly push the image we just built to the registry.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ghumakkad-repo/ghumakkad-backend:latest'

# --- STEP 3: Deploy the image to Cloud Run ---
# This step is the same as before.
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'ghumakkad-backend-service' # Your service name
  - '--image'
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ghumakkad-repo/ghumakkad-backend:latest'
  - '--region'
  - 'asia-south1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'

# -----------------------------------------------------------------

# Tell Cloud Build to use the "latest" image we just built and pushed
images:
- 'asia-south1-docker.pkg.dev/$PROJECT_ID/ghumakkad-repo/ghumakkad-backend:latest'

# This logging option is still correct
options:
  logging: CLOUD_LOGGING_ONLY